vanity = "0x00"
validators = ["0xd8Dba507e85F116b1f7e231cA8525fC9008A6966","0x6571D97f340c8495B661a823F2C2145cA47D63c2","0xe36cbeB565B061217930767886474e3cDe903AC5","0xF512a992F3fb749857d758fFDa1330e590fa915E"]